# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Strangeness in Quark Matter (SQM 2022)
email: yongjun.choi@cern.ch
description: > # this means to ignore newlines until "baseurl:"
  The International Conference on Strangeness in Quark Matter (SQM 2022) will focus on new experimental and theoretical developments on the role of strange quark.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/SQM2022/SQM2022.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: HIPEx
address_line: 2, Busandaehak-ro 63beon-gil Geumjeong-gu Busan, Republic of Korea
telephone_number: 
fax_number: 
company_email: sqm2022@hipex.phys.pusan.ac.kr
google_map: https://www.google.co.kr/maps/search/PNU/@35.2325683,129.0779713,17z/data=!3m1!4b1

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Google analytics
google_analytics_id: G-BDDL11VR0P

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

whitelist:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# permalink: /:collection/:categories/:title/

include:
   - _pages
   - .htaccess

collections:
  sponsors:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:collection/:path/

defaults:
  # 1
  - scope:
      path: "_pages/general-info"
    values:
      category: General
      categoryname: "General Information"
  - scope:
      path: "_pages/committees"
    values:
      category: Committee
      categoryname: "Committee"
  - scope:
      path: "_pages/history"
    values:
      category: History
      categoryname: "History"
  - scope:
      path: "_pages/sponsors"
    values:
      category: Sponsors
      categoryname: "Sponsors"
  - scope:
      path: "_pages/travel-info"
    values:
      category: Travel
      categoryname: "Travel Informations"
  - scope:
      path: "_pages/scientific-info"
    values:
      category: Scientific
      categoryname: "Scientific Information"
  - scope:
      path: "_sponsors"
    values:
      notitle: true
      
      


head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML